### ISSUE TITLE
Error updating NStack on didBecomeActive

### ISSUE THREAD

**Issue by JMCPH** [nodes-ios/TranslationManager#26]
Hi.

I'm using the TranslationManager in a project, and is able to fetch the translations correctly on when building and compiling the app in Xcode. The issue appears when I change a localisation in NStack and open the app. Then the newest translation is missing and I receive the following error:

`[NStackSDK] #error: Error updating NStack on did become active: The operation couldn’t be completed. (NStackSDK.NStackError.Manager error 0.)`

Do you guys have any idea how to debug or find a solution to fix the bug?

**Comment by JMCPH** [comment]
@pbodsk @nickskull @chriscombs @jakobmygind

**Comment by chriscombs** [comment]
Hey, we'll take a look. Thanks for bringing it to our attention

**Comment by chriscombs** [comment]
What version are you using? This should be fixed in the latest version.

**Comment by JMCPH** [comment]
It seems to be fixed, thanks for the quick reply 👍
